on: [push]

jobs:
  output_releases:
    runs-on: ubuntu-latest
    outputs:
      range: ${{ steps.releases.outputs.range }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch Current Releases
        uses: ./
        id: releases

  current_php_releases:
    runs-on: ubuntu-latest
    needs: output_releases
    strategy:
      matrix: ${{ fromJSON(needs.output_releases.outputs.range) }}
    name: PHP ${{ matrix.php }}
    steps:
      - name: Echo PHP
        run: echo ${{ matrix.php }}
