name: Test Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  output_releases:
    name: Generate PHP Releases Array
    runs-on: ubuntu-latest
    outputs:
      range: ${{ steps.releases.outputs.range }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch Current Releases
        uses: ./
        id: releases
        with:
          releases: '7.4, 7.3'

  current_php_releases:
    runs-on: ubuntu-latest
    needs: output_releases
    strategy:
      matrix:
        php: ${{fromJSON(needs.output_releases.outputs.range)}}
    name: PHP ${{ matrix.php }}
    steps:
      - name: Echo PHP
        run: echo ${{ matrix.php }}
